[versions]
agp = "8.9.1"
android-compileSdk = "36"
android-minSdk = "28"
android-targetSdk = "36"
version-code = "10010103" # major(10), minor(01), patch(01), build(00)
version-name = "1.1.1" # major(1), minor(1), patch(1)

# Multiplatform
compose = "1.9.3"
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"
jetbrainsKotlinJvm = "2.2.0"

# androidX
androidx-core-ktx = "1.16.0"
androidx-appcompat = "1.7.1"
androidx-activityCompose = "1.10.1"
sqlite = "2.5.0-rc03"
androidx-datastore = "1.1.7"
androidx-room = "2.7.0-rc03"

# org.jetbrains.kotlinx
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
kotlinx-date-time = "0.7.1"
kotlinx-collections-immutable = "0.4.0"

# org.jetbrains.androidx
jetbrains-androidx-lifecycle = "2.9.6"
jetbrains-androidx-navigation-compose = "2.9.1"

# DI
koin = "4.1.1"
koin-annotation = "2.3.1"

# Network
ktor = "3.3.2"

# Image Loader
coil3 = "3.3.0"

# Permission
moko = "0.20.1"

# Logging
napier = "2.7.1"

# Firebase
gms = "4.4.4"
firebase = "34.5.0"
firebase-crahslytics = "3.0.6"

# Auth
kakao = "2.22.0"

# Deep Link
apps-flyer = "6.17.3"

# Utility
kmp-spm = "1.0.4"
play-review = "2.0.2"

# Test
turbine = "1.2.1"
mokkery = "2.9.0"

# Lint
spotless = "8.0.0"
ktlint-cli = "1.6.0"

[libraries]
# androidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activityCompose" }
sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "androidx-datastore" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidx-datastore" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }

# org.jetbrains.kotlinx
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-date-time = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-date-time" }

# org.jetbrains.androidx
jetbrains-androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "jetbrains-androidx-lifecycle" }
jetbrains-androidx-lifecycle-viewmodel-savestate = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "jetbrains-androidx-lifecycle" }
jetbrains-androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "jetbrains-androidx-lifecycle" }
jetbrains-androidx-compose-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "jetbrains-androidx-navigation-compose" }

# org.jetbrains.compose
jetbrains-compose-ui-backhandler = { group = "org.jetbrains.compose.ui", name = "ui-backhandler", version.ref = "compose" }

# DI
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-annotation = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-annotation" }
koin-ksp-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin-annotation" }

# Network
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }

# Image Loader
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil3" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
coil-mp = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }

# Logging
napier = { module = "io.github.aakira:napier", version.ref = "napier" }

# Permission
moko-permission-compose = { group = "dev.icerock.moko", name = "permissions-compose", version.ref = "moko" }
moko-permission-notifications = { group = "dev.icerock.moko", name = "permissions-notifications", version.ref = "moko" }

# Firebase
firebase-bom-android = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-fcm = { group = "com.google.firebase", name = "firebase-messaging" }

# Auth
kakao-login = { group = "com.kakao.sdk", name = "v2-user", version.ref = "kakao" }

# Deep Link
apps-flyer = { group = "com.appsflyer", name = "af-android-sdk", version.ref = "apps-flyer" }

# Utility
play-review = { group = "com.google.android.play", name = "review-ktx", version.ref = "play-review" }

# Test
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
mokkery = { group = "dev.mokkery", name = "mokkery-gradle", version.ref = "mokkery" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

# Gradle-Plugin
kotlin-gradleplugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-gradleplugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
compose-compiler-gradleplugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-multiplatform-gradleplugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "compose" }
android-gradleplugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
ksp-gradleplugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "androidx-room" }
kmp-spm = { id = "io.github.frankois944.spmForKmp", version.ref = "kmp-spm" }
googleServices = { id = "com.google.gms.google-services", version.ref = "gms" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crahslytics" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
spotless = { id = "com.diffplug.gradle.spotless", version.ref = "spotless" }

[bundles]
ktor = [
    "ktor-client-core",
    "ktor-client-content-negotiation",
    "ktor-client-auth",
    "ktor-client-logging",
    "ktor-serialization-kotlinx-json",
]
coil = [
    "coil-compose",
    "coil-compose-core",
    "coil-network-ktor3",
    "coil-mp"
]
moko = [
    "moko-permission-compose",
    "moko-permission-notifications"
]
datastore = [
    "androidx-datastore",
    "androidx-datastore-preferences"
]
plugins = [
    "kotlin-gradleplugin",
    "kotlin-serialization-gradleplugin",
    "compose-compiler-gradleplugin",
    "compose-multiplatform-gradleplugin",
    "android-gradleplugin",
    "ksp-gradleplugin"
]